# Documentação: https://keda.sh/docs/2.8/scalers/azure-service-bus/
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaledobject
spec:
  scaleTargetRef:
    name: consumer
  pollingInterval: 5
  minReplicaCount: 1
  maxReplicaCount: 30
  triggers:
  - type: azure-servicebus
    metadata:
      connectionFromEnv: ConnectionStrings__AzureServiceBus
      queueName: demo
      messageCount: "50"