apiVersion: v1
kind: Secret
metadata:
  name: consumer-secrets
type: Opaque
data:
  ConnectionAzureServiceBus: RW5kcG9pbnQ9c2I6Ly9mZXN0aXZhbHRlY25vbG9naWFtcy5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PWRLK1FvTmpMOWlwOElVTXFtd25xOC9ZaEpIVnRQVFphNHpvTVd3WUsvdXc9Ow==