apiVersion: v1
kind: Secret
metadata:
  name: consumer-secrets
type: Opaque
data:
  ConnectionAzureServiceBus: RW5kcG9pbnQ9c2I6Ly9mZXN0aXZhbHRlY25vbG9naWFtcy5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPUtleUtlZGE7U2hhcmVkQWNjZXNzS2V5PXp0Y2J4bjBobUZPcnBWS2hqVnhEV0xsQ0hWQkovY2RFY1RNQ1pQWk5KVXM9O0VudGl0eVBhdGg9ZGVtbw==